# Use the official PHP image with Apache
FROM php:7.4-apache

# MySQLi extension 
RUN docker-php-ext-install mysqli

# For .htaccess
RUN a2enmod rewrite

# Expose port 80 for Apache
EXPOSE 80

# Copy your application code into the container
COPY ./vendor /var/www/html/

# Set the working directory to the Apache root directory
WORKDIR /var/www/html/

