services:
  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    depends_on:
      - database

  vendor:
    build:
      context: ./vendor
      dockerfile: Dockerfile.apache
    volumes:
      - ./vendor:/var/www/html
    depends_on:
      - database
    ports:
      - "8080:80"

  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

    