FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --unsafe-perm

RUN npm install -g nodemon

RUN npm install -g cookie-parser

COPY . .

EXPOSE 3000

CMD ["npm", "run", "demon"]